using DevExpress.XtraTreeList;
using System;
using System.Drawing;
using System.Windows.Forms;

namespace Ketoan.Controls.BanHangPhaiThu.BaoCao
{
    public partial class MenuBaoCao : UserControl
    {
        public MenuBaoCao()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            e004MBHPTTableAdapter1.Fill(ewondataset1.E004MBHPT);
        }

        private void treeList1_DoubleClick(object sender, EventArgs e)
        {
            Point fPoint = Control.MousePosition;
            TreeList tl = (TreeList)sender;
            fPoint = tl.PointToClient(fPoint);
            TreeListHitInfo hInfo = tl.CalcHitInfo(fPoint);
            if (hInfo.Node != null)
            {
                Text = hInfo.Node.GetDisplayText(1);
                FBaoCaoMuaHang bc = new FBaoCaoMuaHang(Text);
                bc.Show();
            }
        }
    }
}
