using DevExpress.XtraTreeList;
using Ketoan.Controls.DungChung.Menu;
using System;
using System.Drawing;
using System.Windows.Forms;

namespace Ketoan.Controls.HangTonKho.BaoCao
{
    public partial class BaoCao : UserControl
    {
        public BaoCao()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //e004MBCKTableAdapter1.Fill(ewondataset1.E004MBCK);
        }

        //private int count = 0;
        //private void treeList1_FocusedNodeChanged(object sender, DevExpress.XtraTreeList.FocusedNodeChangedEventArgs e)
        //{
        //    if (count >= 1)
        //    {
        //        string t = e.Node.GetValue(treeList1.KeyFieldName).ToString();
        //        string value=e.Node.GetValue("tenmenu").ToString();
        //        FBaocaotonkho bc = new FBaocaotonkho(value);
        //        bc.Show();
        //    }
        //    count = count + 1;
        //}

        private void treeList1_DoubleClick(object sender, EventArgs e)
        {
            Point fPoint = Control.MousePosition;
            TreeList tl= (TreeList)sender;
            fPoint = tl.PointToClient(fPoint);
            TreeListHitInfo hInfo = tl.CalcHitInfo(fPoint);
            if (hInfo.Node != null)
            {
                Text = hInfo.Node.GetDisplayText(1);
                FBaoCaoTonKho bc = new FBaoCaoTonKho(Text);
                bc.Show();
            }
        }
    }
}

