using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMKHO : UserControl
    {
        public EDMKHO()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Dock = DockStyle.Fill;
            e00DMKHOTableAdapter1.Fill(ewondataset1.E00DMKHO);
        }
    }
}
