using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMKV : UserControl
    {
        public EDMKV()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Dock = DockStyle.Fill;
            e00DMKVTableAdapter1.Fill(ewondataset1.E00DMKV);
        }
    }
}
