using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMKM : UserControl
    {
        public EDMKM()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Dock = DockStyle.Fill;
            e00DMKMTableAdapter1.Fill(ewondataset1.E00DMKM);
        }
    }
}
