using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMNHVT : UserControl
    {
        public EDMNHVT()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Dock = DockStyle.Fill;
            e00DMNHVTTableAdapter1.Fill(ewondataset1.E00DMNHVT);
        }
    }
}
