using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMNHNHAN : UserControl
    {
        public EDMNHNHAN()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Dock = DockStyle.Fill;
            e00DMNHANTableAdapter1.Fill(ewondataset1.E00DMNHAN);
        }
    }
}
