using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMBP : UserControl
    {
        public EDMBP()
        {
            InitializeComponent();
            //eDMBPTableAdapter.Fill(eWONDataSet.EDMBP);
            // This line of code is generated by Data Source Configuration Wizard
            e00DMBPTableAdapters.Fill(ewondatasets.E00DMBP);
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {

        }
    }
}
