using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMKV : UserControl
    {
        public EDMKV()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            e00DMKVTableAdapter1.Fill(ewondataset1.E00DMKV);
        }
    }
}
