using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMKM : UserControl
    {
        public EDMKM()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            e00DMKMTableAdapter1.Fill(ewondataset1.E00DMKM);
        }

        private void EDMKM_Load(object sender, EventArgs e)
        {

        }

        private void gridControl2_Click(object sender, EventArgs e)
        {

        }
    }
}
