using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMKHO : UserControl
    {
        public EDMKHO()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            e00DMKHOTableAdapter1.Fill(ewondataset1.E00DMKHO);
        }

        private void EDMKHO_Load(object sender, EventArgs e)
        {

        }

        private void eWONDATASETBindingSource_CurrentChanged(object sender, EventArgs e)
        {
                    }
    }
}
