using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMLO : UserControl
    {
        public EDMLO()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Dock = DockStyle.Fill;
            e00DMLOTableAdapter1.Fill(ewondataset1.E00DMLO);
        }
    }
}
