using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMNHDT : UserControl
    {
        public EDMNHDT()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            e00DMNHDTTableAdapter1.Fill(ewondataset1.E00DMNHDT);
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
    }
}
