using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMPLHD : UserControl
    {
        public EDMPLHD()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Dock = DockStyle.Fill;
            e00DMPLHDTableAdapter1.Fill(ewondataset1.E00DMPLHD);
        }
    }
}
