using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMTK : UserControl
    {
        public EDMTK()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Dock = DockStyle.Fill;
            e00DMTKTableAdapter1.Fill(ewondataset1.E00DMTK);
        }
    }
}
