using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMTHUE : UserControl
    {
        public EDMTHUE()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Dock = DockStyle.Fill;
            e00DMTHUETableAdapter1.Fill(ewondataset1.E00DMTHUE);
        }
    }
}
