using System.Windows.Forms;

namespace Ketoan.Table
{
    public partial class EDMYT : UserControl
    {
        public EDMYT()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Dock = DockStyle.Fill;
            e00DMYTTableAdapter1.Fill(ewondataset1.E00DMYT);
        }
    }
}
